name: Despliegue Automático

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Determinar archivo de configuración según la rama
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            export CONFIG_FILE=./cicd/config-dev.env
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            export CONFIG_FILE=./cicd/config-prod.env
          else
            echo "Rama desconocida, no se cargará ningún archivo de configuración."
            exit 1
          fi
          echo "Archivo de configuración seleccionado: $CONFIG_FILE"
          source $CONFIG_FILE

      - name: Ejecutar script para obtener el código
        run: |
          bash ./cicd/1-pull-code.sh

      - name: Ejecutar script para construir la imagen
        run: |
          bash ./cicd/2-build-image.sh

      - name: Ejecutar script para subir la imagen
        run: |
          bash ./cicd/3-push-image.sh

      - name: Ejecutar script para aplicar en Kubernetes
        run: |
          bash ./cicd/4-k8s-apply.sh
